#常量
SCREEN_W,SCREEN_H=800,600
SCREEN_SIZE=(SCREEN_W,SCREEN_H)
GROUND_HEIGHT=SCREEN_H-62    #地面高度

BG_MULTI=2.68
PLAYER_MULTI=2.9     #mario放大倍数
BRICK_MULTI=2.69    #砖块放大倍数
ENEMY_MULTI=2.5      #敌人的放大倍数
ENEMY_SPEED=1    #敌人的速度

FONT='FixedSys.ttf'
GRAVITY=1.0    #重力加速度
ANTI_GRAVITY=0.3